# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34249468fa472532021501500cedb7db6874a2d5b697b0d635806f62b6cd2eea859490048ded34c47dcbf59537217c464d0614f42f1ab1ed91977808ba990408

test:
  secret_key_base: 34c9188e608a6e1e8dc05389193d4d1cc82c25fba4c9812dfafe02d4a1d3d9d15402373fe100c79679eababd9bcb3ad1fc0797da5ba36450ee145e7e0d1cdc40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
